{{- if .Values.pvProvisioner.enabled -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: aws-efs-csi-pv-provisioner-root
spec:
  capacity:
    storage: 1Mi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  mountOptions:
  - tls
  - iam
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: {{ template aws-efs-csi.fsId }}:/
{{- end}}
