{{- if .Values.pvProvisioner.enabled -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: aws-efs-csi-pv-provisioner-root
spec:
  capacity:
    storage: 1Mi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
{{- with .Values.pvProvisioner.rootPV.mountOptions }}
  mountOptions:
    {{- toYaml . | nindent 4 }}
{{- end }}
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: {{ include "aws-efs-csi.fsId" . }}:/
{{- end}}
