{{- if .Values.pvProvisioner.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aws-efs-csi-pv-provisioner-root
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 1Mi
{{- end }}
