{{- if .Values.pvProvisioner.enabled -}}
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: efs
provisioner: aws.k8s.logmein.com/efs-csi-pv-provisioner
{{- with .Values.pvProvisioner.storageClass.mountOptions }}
mountOptions:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
